or(
Var5 = FRAN  and Var59 = SRUNLI
Var5 = DOTO  and Var59 = SRUNLI
Var5 = ALLE  and Var59 = SRUNLI
Var5 = AUTR  and Var59 = SRUNLI
Var5 = BELG  and Var59 = SRUNLI
Var5 = DANE  and Var59 = RUNLI
Var5 = ESPA  and Var59 = SRUNLI
Var5 = FINL  and Var59 = RUNLI
Var5 = GRBR  and Var59 = SRUNLI
Var5 = GREC  and Var59 = SRUNLI
Var5 = HOLL  and Var59 = SRUNLI
Var5 = IRLA  and Var59 = SRUNLI
Var5 = ISLA  and Var59 = SRUNLI
Var5 = ITAL  and Var59 = SRUNLI
Var5 = NORV  and Var59 = RUNLI
Var5 = PORT  and Var59 = SRUNLI
Var5 = SUED  and Var59 = RUNLI
Var5 = SUIS  and Var59 = SRUNLI
Var5 = YOUG  and Var59 = SRUNLI
Var5 = MAGH  and Var59 = SRUNLI
Var5 = TURQ  and Var59 = SRUNLI
Var5 = ARGE  and Var59 = SRUNLI
Var5 = BRES  and Var59 = SRUNLI
Var5 = CHIL  and Var59 = SRUNLI
Var5 = COLO  and Var59 = SRUNLI
Var5 = AFSU  and Var59 = SRUNLI
Var5 = MARO  and Var59 = SRUNLI
Var5 = ISRA  and Var59 = SRUNLI
Var5 = HONG  and Var59 = SRUNLI
Var5 = TCHE  and Var59 = SRUNLI
Var5 = POLO  and Var59 = SRUNLI
Var5 = SLVQ  and Var59 = SRUNLI
Var5 = JAPO  and Var59 = SRUNLI
Var5 = TAIW  and Var59 = SRUNLI
Var5 = AUST  and Var59 = SRUNLI
Var5 = URUG  and Var59 = SRUNLI
Var5 = DAIB  and Var59 = SRUNLI
Var5 = DAIC  and Var59 = SRUNLI
Var5 = DAID  and Var59 = SRUNLI
Var5 = DAIF  and Var59 = SRUNLI
Var5 = EUOR  and Var59 = SRUNLI
Var5 = CETI  and Var59 = SRUNLI
or)