or(
Var5 = FRAN  and Var39 = CATADI
Var5 = DOTO  and Var39 = CATADI
Var5 = ALLE  and Var39 = CATADI
Var5 = AUTR  and Var39 = CATADI
Var5 = BELG  and Var39 = CATADI
Var5 = DANE  and Var39 = CATADI
Var5 = ESPA  and Var39 = CATADI
Var5 = FINL  and Var39 = CATADI
Var5 = GRBR  and Var39 = CATADI
Var5 = GREC  and Var39 = CATADI
Var5 = HOLL  and Var39 = CATADI
Var5 = IRLA  and Var39 = CATADI
Var5 = ISLA  and Var39 = CATADI
Var5 = ITAL  and Var39 = CATADI
Var5 = NORV  and Var39 = CATADI
Var5 = PORT  and Var39 = CATADI
Var5 = SUED  and Var39 = CATADI
Var5 = SUIS  and Var39 = CATADI
Var5 = YOUG  and Var39 = CATADI
Var5 = MAGH  and Var39 = SCATAD
Var5 = TURQ  and Var39 = SCATAD
Var5 = ARGE  and Var39 = SCATAD
Var5 = BRES  and Var39 = SCATAD
Var5 = CHIL  and Var39 = CATADI
Var5 = COLO  and Var39 = SCATAD
Var5 = AFSU  and Var39 = CATADI
Var5 = MARO  and Var39 = SCATAD
Var5 = ISRA  and Var39 = CATADI
Var5 = HONG  and Var39 = CATADI
Var5 = TCHE  and Var39 = CATADI
Var5 = POLO  and Var39 = CATADI
Var5 = SLVQ  and Var39 = CATADI
Var5 = JAPO  and Var39 = CATADI
Var5 = TAIW  and Var39 = CATADI
Var5 = AUST  and Var39 = CATADI
Var5 = URUG  and Var39 = CATADI
Var5 = DAIB  and Var39 = SCATAD
Var5 = DAIC  and Var39 = SCATAD
Var5 = DAID  and Var39 = CATADI
Var5 = DAIF  and Var39 = SCATAD
Var5 = EUOR  and Var39 = CATADI
Var5 = CETI  and Var39 = SCATAD
or)