or(
Var5 = FRAN  and Var36 = PTCAV
Var5 = DOTO  and Var36 = PTCAV
Var5 = ALLE  and Var36 = PTCAV
Var5 = AUTR  and Var36 = PTCAV
Var5 = BELG  and Var36 = PTCAV
Var5 = DANE  and Var36 = PTCAV
Var5 = ESPA  and Var36 = PTCAV
Var5 = FINL  and Var36 = PTCAV
Var5 = GRBR  and Var36 = PTCAV
Var5 = GREC  and Var36 = PTCAV
Var5 = HOLL  and Var36 = PTCAV
Var5 = IRLA  and Var36 = PTCAV
Var5 = ISLA  and Var36 = PTCAV
Var5 = ITAL  and Var36 = PTCAV
Var5 = NORV  and Var36 = PTCAV
Var5 = PORT  and Var36 = PTCAV
Var5 = SUED  and Var36 = PTCAV
Var5 = SUIS  and Var36 = PTCAV
Var5 = YOUG  and Var36 = PTCAV
Var5 = MAGH  and Var36 = PTCAV
Var5 = TURQ  and Var36 = PTCAV
Var5 = ARGE  and Var36 = PTCAV
Var5 = BRES  and Var36 = PTCAV
Var5 = CHIL  and Var36 = PTCAV
Var5 = COLO  and Var36 = PTCAV
Var5 = AFSU  and Var36 = PTCAV
Var5 = MARO  and Var36 = PTCAV
Var5 = ISRA  and Var36 = PTCAV
Var5 = HONG  and Var36 = PTCAV
Var5 = TCHE  and Var36 = PTCAV
Var5 = POLO  and Var36 = PTCAV
Var5 = SLVQ  and Var36 = PTCAV
Var5 = JAPO  and Var36 = PTCAV
Var5 = TAIW  and Var36 = PTCAV
Var5 = AUST  and Var36 = PTCAV
Var5 = URUG  and Var36 = PTCAV
Var5 = DAIB  and Var36 = PTCAV
Var5 = DAIC  and Var36 = PTCAV
Var5 = DAID  and Var36 = PTCAV
Var5 = DAIF  and Var36 = PTCAV
Var5 = EUOR  and Var36 = PTCAV
Var5 = CETI  and Var36 = PTCAV
or)