or(
Var5 = FRAN  and Var71 = FSTPO
Var5 = DOTO  and Var71 = FSTPO
Var5 = ALLE  and Var71 = FSTPO
Var5 = AUTR  and Var71 = FSTPO
Var5 = BELG  and Var71 = FSTPO
Var5 = DANE  and Var71 = FSTPO
Var5 = ESPA  and Var71 = FSTPO
Var5 = FINL  and Var71 = FSTPO
Var5 = GRBR  and Var71 = FSTPO
Var5 = GREC  and Var71 = FSTPO
Var5 = HOLL  and Var71 = FSTPO
Var5 = IRLA  and Var71 = FSTPO
Var5 = ISLA  and Var71 = FSTPO
Var5 = ITAL  and Var71 = FSTPO
Var5 = NORV  and Var71 = FSTPO
Var5 = PORT  and Var71 = FSTPO
Var5 = SUED  and Var71 = FSTPO
Var5 = SUIS  and Var71 = FSTPO
Var5 = YOUG  and Var71 = FSTPO
Var5 = MAGH  and Var71 = FSTPO
Var5 = TURQ  and Var71 = FSTPO
Var5 = ARGE  and Var71 = FSTPO
Var5 = BRES  and Var71 = FSTPO
Var5 = CHIL  and Var71 = FSTPO
Var5 = COLO  and Var71 = FSTPO
Var5 = AFSU  and Var71 = FSTPO
Var5 = MARO  and Var71 = FSTPO
Var5 = ISRA  and Var71 = FSTPO
Var5 = HONG  and Var71 = FSTPO
Var5 = TCHE  and Var71 = FSTPO
Var5 = POLO  and Var71 = FSTPO
Var5 = SLVQ  and Var71 = FSTPO
Var5 = JAPO  and Var71 = FSTPO
Var5 = TAIW  and Var71 = FSTPO
Var5 = AUST  and Var71 = FSTPO
Var5 = URUG  and Var71 = FSTPO
Var5 = DAIB  and Var71 = FSTPO
Var5 = DAIC  and Var71 = FSTPO
Var5 = DAID  and Var71 = FSTPO
Var5 = DAIF  and Var71 = FSTPO
Var5 = EUOR  and Var71 = FSTPO
Var5 = CETI  and Var71 = FSTPO
or)