or(
Var3 = M5  and Var9 = DM  and Var11 = SSABS
Var3 = M5  and Var9 = DA  and Var11 = SSABS
Var3 = M5  and Var9 = DA  and Var11 = ABS
Var3 = M6  and Var9 = DM  and Var11 = SSABS
Var3 = M6  and Var9 = DA  and Var11 = SSABS
Var3 = M6  and Var9 = DA  and Var11 = ABS
Var3 = M7  and Var9 = DM  and Var11 = SSABS
Var3 = M7  and Var9 = DA  and Var11 = SSABS
Var3 = M7  and Var9 = DA  and Var11 = ABS
Var3 = M8  and Var9 = DM  and Var11 = SSABS
Var3 = M8  and Var9 = DA  and Var11 = SSABS
Var3 = M8  and Var9 = DA  and Var11 = ABS
Var3 = M9  and Var9 = DM  and Var11 = SSABS
Var3 = M9  and Var9 = DA  and Var11 = SSABS
Var3 = M9  and Var9 = DA  and Var11 = ABS
Var3 = MA  and Var9 = DM  and Var11 = SSABS
Var3 = MA  and Var9 = DA  and Var11 = SSABS
Var3 = MA  and Var9 = DA  and Var11 = ABS
Var3 = MB  and Var9 = DM  and Var11 = SSABS
Var3 = MB  and Var9 = DA  and Var11 = SSABS
Var3 = MB  and Var9 = DA  and Var11 = ABS
Var3 = MC  and Var9 = DM  and Var11 = SSABS
Var3 = MC  and Var9 = DA  and Var11 = SSABS
Var3 = MC  and Var9 = DA  and Var11 = ABS
Var3 = MD  and Var9 = DM  and Var11 = SSABS
Var3 = MD  and Var9 = DA  and Var11 = SSABS
Var3 = MD  and Var9 = DA  and Var11 = ABS
Var3 = ME  and Var9 = DM  and Var11 = SSABS
Var3 = ME  and Var9 = DA  and Var11 = SSABS
Var3 = ME  and Var9 = DA  and Var11 = ABS
Var3 = MF  and Var9 = DM  and Var11 = SSABS
Var3 = MF  and Var9 = DA  and Var11 = SSABS
Var3 = MF  and Var9 = DA  and Var11 = ABS
Var3 = MJ  and Var9 = DM  and Var11 = SSABS
Var3 = MJ  and Var9 = DA  and Var11 = SSABS
Var3 = MJ  and Var9 = DA  and Var11 = ABS
Var3 = MK  and Var9 = DM  and Var11 = SSABS
Var3 = MK  and Var9 = DA  and Var11 = SSABS
Var3 = MK  and Var9 = DA  and Var11 = ABS
Var3 = ML  and Var9 = DM  and Var11 = SSABS
Var3 = ML  and Var9 = DA  and Var11 = SSABS
Var3 = ML  and Var9 = DA  and Var11 = ABS
Var3 = MM  and Var9 = DM  and Var11 = SSABS
Var3 = MM  and Var9 = DA  and Var11 = SSABS
Var3 = MM  and Var9 = DA  and Var11 = ABS
Var3 = MS  and Var9 = DM  and Var11 = SSABS
Var3 = MS  and Var9 = DA  and Var11 = SSABS
Var3 = MS  and Var9 = DA  and Var11 = ABS
Var3 = MT  and Var9 = DM  and Var11 = SSABS
Var3 = MT  and Var9 = DM  and Var11 = ABS
Var3 = MT  and Var9 = DA  and Var11 = SSABS
Var3 = MT  and Var9 = DA  and Var11 = ABS
Var3 = MU  and Var9 = DM  and Var11 = SSABS
Var3 = MU  and Var9 = DA  and Var11 = SSABS
Var3 = MU  and Var9 = DA  and Var11 = ABS
Var3 = MN  and Var9 = DM  and Var11 = SSABS
Var3 = MN  and Var9 = DA  and Var11 = SSABS
Var3 = MN  and Var9 = DA  and Var11 = ABS
Var3 = MH  and Var9 = DM  and Var11 = SSABS
Var3 = MH  and Var9 = DA  and Var11 = SSABS
Var3 = MH  and Var9 = DA  and Var11 = ABS
Var3 = MG  and Var9 = DM  and Var11 = SSABS
Var3 = MG  and Var9 = DA  and Var11 = SSABS
Var3 = MG  and Var9 = DA  and Var11 = ABS
Var3 = MY  and Var9 = DM  and Var11 = SSABS
Var3 = MY  and Var9 = DA  and Var11 = SSABS
Var3 = MY  and Var9 = DA  and Var11 = ABS
Var3 = NM2K  and Var9 = DM  and Var11 = SSABS
Var3 = NM2K  and Var9 = DA  and Var11 = SSABS
Var3 = NM2K  and Var9 = DA  and Var11 = ABS
Var3 = NM0C  and Var9 = DM  and Var11 = SSABS
Var3 = NM0C  and Var9 = DM  and Var11 = ABS
Var3 = NM0C  and Var9 = DA  and Var11 = SSABS
Var3 = NM0C  and Var9 = DA  and Var11 = ABS
Var3 = ND1G  and Var9 = DM  and Var11 = SSABS
Var3 = ND1G  and Var9 = DA  and Var11 = SSABS
Var3 = ND1G  and Var9 = DA  and Var11 = ABS
or)