or(
Var5 = FRAN  and Var11 = SSABS  and Var45 = SUSREN
Var5 = FRAN  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = FRAN  and Var11 = ABS  and Var45 = SUSREN
Var5 = FRAN  and Var11 = ABS  and Var45 = SUSNOR
Var5 = DOTO  and Var11 = SSABS  and Var45 = SUSREN
Var5 = DOTO  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = DOTO  and Var11 = ABS  and Var45 = SUSREN
Var5 = DOTO  and Var11 = ABS  and Var45 = SUSNOR
Var5 = ALLE  and Var11 = SSABS  and Var45 = SUSREN
Var5 = ALLE  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = ALLE  and Var11 = ABS  and Var45 = SUSREN
Var5 = ALLE  and Var11 = ABS  and Var45 = SUSNOR
Var5 = AUTR  and Var11 = SSABS  and Var45 = SUSREN
Var5 = AUTR  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = AUTR  and Var11 = ABS  and Var45 = SUSREN
Var5 = AUTR  and Var11 = ABS  and Var45 = SUSNOR
Var5 = BELG  and Var11 = SSABS  and Var45 = SUSREN
Var5 = BELG  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = BELG  and Var11 = ABS  and Var45 = SUSREN
Var5 = BELG  and Var11 = ABS  and Var45 = SUSNOR
Var5 = DANE  and Var11 = SSABS  and Var45 = SUSREN
Var5 = DANE  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = DANE  and Var11 = ABS  and Var45 = SUSREN
Var5 = DANE  and Var11 = ABS  and Var45 = SUSNOR
Var5 = ESPA  and Var11 = SSABS  and Var45 = SUSREN
Var5 = ESPA  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = ESPA  and Var11 = ABS  and Var45 = SUSREN
Var5 = ESPA  and Var11 = ABS  and Var45 = SUSNOR
Var5 = FINL  and Var11 = SSABS  and Var45 = SUSREN
Var5 = FINL  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = FINL  and Var11 = ABS  and Var45 = SUSREN
Var5 = FINL  and Var11 = ABS  and Var45 = SUSNOR
Var5 = GRBR  and Var11 = SSABS  and Var45 = SUSREN
Var5 = GRBR  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = GRBR  and Var11 = ABS  and Var45 = SUSREN
Var5 = GRBR  and Var11 = ABS  and Var45 = SUSNOR
Var5 = GREC  and Var11 = SSABS  and Var45 = SUSREN
Var5 = GREC  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = GREC  and Var11 = ABS  and Var45 = SUSREN
Var5 = GREC  and Var11 = ABS  and Var45 = SUSNOR
Var5 = HOLL  and Var11 = SSABS  and Var45 = SUSREN
Var5 = HOLL  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = HOLL  and Var11 = ABS  and Var45 = SUSREN
Var5 = HOLL  and Var11 = ABS  and Var45 = SUSNOR
Var5 = IRLA  and Var11 = SSABS  and Var45 = SUSREN
Var5 = IRLA  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = IRLA  and Var11 = ABS  and Var45 = SUSREN
Var5 = IRLA  and Var11 = ABS  and Var45 = SUSNOR
Var5 = ISLA  and Var11 = SSABS  and Var45 = SUSREN
Var5 = ISLA  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = ISLA  and Var11 = ABS  and Var45 = SUSREN
Var5 = ISLA  and Var11 = ABS  and Var45 = SUSNOR
Var5 = ITAL  and Var11 = SSABS  and Var45 = SUSREN
Var5 = ITAL  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = ITAL  and Var11 = ABS  and Var45 = SUSREN
Var5 = ITAL  and Var11 = ABS  and Var45 = SUSNOR
Var5 = NORV  and Var11 = SSABS  and Var45 = SUSREN
Var5 = NORV  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = NORV  and Var11 = ABS  and Var45 = SUSREN
Var5 = NORV  and Var11 = ABS  and Var45 = SUSNOR
Var5 = PORT  and Var11 = SSABS  and Var45 = SUSREN
Var5 = PORT  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = PORT  and Var11 = ABS  and Var45 = SUSREN
Var5 = PORT  and Var11 = ABS  and Var45 = SUSNOR
Var5 = SUED  and Var11 = SSABS  and Var45 = SUSREN
Var5 = SUED  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = SUED  and Var11 = ABS  and Var45 = SUSREN
Var5 = SUED  and Var11 = ABS  and Var45 = SUSNOR
Var5 = SUIS  and Var11 = SSABS  and Var45 = SUSREN
Var5 = SUIS  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = SUIS  and Var11 = ABS  and Var45 = SUSREN
Var5 = SUIS  and Var11 = ABS  and Var45 = SUSNOR
Var5 = YOUG  and Var11 = SSABS  and Var45 = SUSREN
Var5 = YOUG  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = YOUG  and Var11 = ABS  and Var45 = SUSREN
Var5 = YOUG  and Var11 = ABS  and Var45 = SUSNOR
Var5 = MAGH  and Var11 = SSABS  and Var45 = SUSREN
Var5 = MAGH  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = MAGH  and Var11 = ABS  and Var45 = SUSNOR
Var5 = TURQ  and Var11 = SSABS  and Var45 = SUSREN
Var5 = TURQ  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = TURQ  and Var11 = ABS  and Var45 = SUSREN
Var5 = TURQ  and Var11 = ABS  and Var45 = SUSNOR
Var5 = ARGE  and Var11 = SSABS  and Var45 = SUSREN
Var5 = ARGE  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = ARGE  and Var11 = ABS  and Var45 = SUSREN
Var5 = ARGE  and Var11 = ABS  and Var45 = SUSNOR
Var5 = BRES  and Var11 = SSABS  and Var45 = SUSREN
Var5 = BRES  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = BRES  and Var11 = ABS  and Var45 = SUSREN
Var5 = BRES  and Var11 = ABS  and Var45 = SUSNOR
Var5 = CHIL  and Var11 = SSABS  and Var45 = SUSREN
Var5 = CHIL  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = CHIL  and Var11 = ABS  and Var45 = SUSREN
Var5 = CHIL  and Var11 = ABS  and Var45 = SUSNOR
Var5 = COLO  and Var11 = SSABS  and Var45 = SUSREN
Var5 = COLO  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = COLO  and Var11 = ABS  and Var45 = SUSREN
Var5 = COLO  and Var11 = ABS  and Var45 = SUSNOR
Var5 = AFSU  and Var11 = SSABS  and Var45 = SUSREN
Var5 = AFSU  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = AFSU  and Var11 = ABS  and Var45 = SUSREN
Var5 = AFSU  and Var11 = ABS  and Var45 = SUSNOR
Var5 = MARO  and Var11 = SSABS  and Var45 = SUSREN
Var5 = MARO  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = MARO  and Var11 = ABS  and Var45 = SUSNOR
Var5 = ISRA  and Var11 = SSABS  and Var45 = SUSREN
Var5 = ISRA  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = ISRA  and Var11 = ABS  and Var45 = SUSREN
Var5 = ISRA  and Var11 = ABS  and Var45 = SUSNOR
Var5 = HONG  and Var11 = SSABS  and Var45 = SUSREN
Var5 = HONG  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = HONG  and Var11 = ABS  and Var45 = SUSREN
Var5 = HONG  and Var11 = ABS  and Var45 = SUSNOR
Var5 = TCHE  and Var11 = SSABS  and Var45 = SUSREN
Var5 = TCHE  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = TCHE  and Var11 = ABS  and Var45 = SUSREN
Var5 = TCHE  and Var11 = ABS  and Var45 = SUSNOR
Var5 = POLO  and Var11 = SSABS  and Var45 = SUSREN
Var5 = POLO  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = POLO  and Var11 = ABS  and Var45 = SUSREN
Var5 = POLO  and Var11 = ABS  and Var45 = SUSNOR
Var5 = SLVQ  and Var11 = SSABS  and Var45 = SUSREN
Var5 = SLVQ  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = SLVQ  and Var11 = ABS  and Var45 = SUSREN
Var5 = SLVQ  and Var11 = ABS  and Var45 = SUSNOR
Var5 = JAPO  and Var11 = SSABS  and Var45 = SUSREN
Var5 = JAPO  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = JAPO  and Var11 = ABS  and Var45 = SUSREN
Var5 = JAPO  and Var11 = ABS  and Var45 = SUSNOR
Var5 = TAIW  and Var11 = SSABS  and Var45 = SUSREN
Var5 = TAIW  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = TAIW  and Var11 = ABS  and Var45 = SUSREN
Var5 = TAIW  and Var11 = ABS  and Var45 = SUSNOR
Var5 = AUST  and Var11 = SSABS  and Var45 = SUSREN
Var5 = AUST  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = AUST  and Var11 = ABS  and Var45 = SUSREN
Var5 = AUST  and Var11 = ABS  and Var45 = SUSNOR
Var5 = URUG  and Var11 = SSABS  and Var45 = SUSREN
Var5 = URUG  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = URUG  and Var11 = ABS  and Var45 = SUSREN
Var5 = URUG  and Var11 = ABS  and Var45 = SUSNOR
Var5 = DAIB  and Var11 = SSABS  and Var45 = SUSREN
Var5 = DAIB  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = DAIB  and Var11 = ABS  and Var45 = SUSNOR
Var5 = DAIC  and Var11 = SSABS  and Var45 = SUSREN
Var5 = DAIC  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = DAIC  and Var11 = ABS  and Var45 = SUSREN
Var5 = DAIC  and Var11 = ABS  and Var45 = SUSNOR
Var5 = DAID  and Var11 = SSABS  and Var45 = SUSREN
Var5 = DAID  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = DAID  and Var11 = ABS  and Var45 = SUSREN
Var5 = DAID  and Var11 = ABS  and Var45 = SUSNOR
Var5 = DAIF  and Var11 = SSABS  and Var45 = SUSREN
Var5 = DAIF  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = DAIF  and Var11 = ABS  and Var45 = SUSREN
Var5 = DAIF  and Var11 = ABS  and Var45 = SUSNOR
Var5 = EUOR  and Var11 = SSABS  and Var45 = SUSREN
Var5 = EUOR  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = EUOR  and Var11 = ABS  and Var45 = SUSREN
Var5 = EUOR  and Var11 = ABS  and Var45 = SUSNOR
Var5 = CETI  and Var11 = SSABS  and Var45 = SUSREN
Var5 = CETI  and Var11 = SSABS  and Var45 = SUSNOR
Var5 = CETI  and Var11 = ABS  and Var45 = SUSNOR
or)