or(
Var3 = M5  and Var5 = FRAN  and Var6 = DG
Var3 = M5  and Var5 = DOTO  and Var6 = DG
Var3 = M5  and Var5 = ALLE  and Var6 = DG
Var3 = M5  and Var5 = AUTR  and Var6 = DG
Var3 = M5  and Var5 = BELG  and Var6 = DG
Var3 = M5  and Var5 = DANE  and Var6 = DG
Var3 = M5  and Var5 = ESPA  and Var6 = DG
Var3 = M5  and Var5 = FINL  and Var6 = DG
Var3 = M5  and Var5 = GRBR  and Var6 = DD
Var3 = M5  and Var5 = GREC  and Var6 = DG
Var3 = M5  and Var5 = HOLL  and Var6 = DG
Var3 = M5  and Var5 = IRLA  and Var6 = DD
Var3 = M5  and Var5 = ISLA  and Var6 = DG
Var3 = M5  and Var5 = ITAL  and Var6 = DG
Var3 = M5  and Var5 = NORV  and Var6 = DG
Var3 = M5  and Var5 = PORT  and Var6 = DG
Var3 = M5  and Var5 = SUED  and Var6 = DG
Var3 = M5  and Var5 = SUIS  and Var6 = DG
Var3 = M5  and Var5 = YOUG  and Var6 = DG
Var3 = M5  and Var5 = MAGH  and Var6 = DG
Var3 = M5  and Var5 = TURQ  and Var6 = DG
Var3 = M5  and Var5 = ARGE  and Var6 = DG
Var3 = M5  and Var5 = BRES  and Var6 = DG
Var3 = M5  and Var5 = CHIL  and Var6 = DG
Var3 = M5  and Var5 = COLO  and Var6 = DG
Var3 = M5  and Var5 = AFSU  and Var6 = DD
Var3 = M5  and Var5 = MARO  and Var6 = DG
Var3 = M5  and Var5 = ISRA  and Var6 = DG
Var3 = M5  and Var5 = HONG  and Var6 = DG
Var3 = M5  and Var5 = TCHE  and Var6 = DG
Var3 = M5  and Var5 = POLO  and Var6 = DG
Var3 = M5  and Var5 = SLVQ  and Var6 = DG
Var3 = M5  and Var5 = JAPO  and Var6 = DD
Var3 = M5  and Var5 = TAIW  and Var6 = DG
Var3 = M5  and Var5 = AUST  and Var6 = DD
Var3 = M5  and Var5 = URUG  and Var6 = DG
Var3 = M5  and Var5 = DAIB  and Var6 = DG
Var3 = M5  and Var5 = DAIC  and Var6 = DG
Var3 = M5  and Var5 = DAID  and Var6 = DD
Var3 = M5  and Var5 = DAIF  and Var6 = DG
Var3 = M5  and Var5 = EUOR  and Var6 = DG
Var3 = M5  and Var5 = CETI  and Var6 = DG
Var3 = M6  and Var5 = FRAN  and Var6 = DG
Var3 = M6  and Var5 = DOTO  and Var6 = DG
Var3 = M6  and Var5 = ALLE  and Var6 = DG
Var3 = M6  and Var5 = AUTR  and Var6 = DG
Var3 = M6  and Var5 = BELG  and Var6 = DG
Var3 = M6  and Var5 = DANE  and Var6 = DG
Var3 = M6  and Var5 = ESPA  and Var6 = DG
Var3 = M6  and Var5 = FINL  and Var6 = DG
Var3 = M6  and Var5 = GRBR  and Var6 = DD
Var3 = M6  and Var5 = GREC  and Var6 = DG
Var3 = M6  and Var5 = HOLL  and Var6 = DG
Var3 = M6  and Var5 = IRLA  and Var6 = DD
Var3 = M6  and Var5 = ISLA  and Var6 = DG
Var3 = M6  and Var5 = ITAL  and Var6 = DG
Var3 = M6  and Var5 = NORV  and Var6 = DG
Var3 = M6  and Var5 = PORT  and Var6 = DG
Var3 = M6  and Var5 = SUED  and Var6 = DG
Var3 = M6  and Var5 = SUIS  and Var6 = DG
Var3 = M6  and Var5 = YOUG  and Var6 = DG
Var3 = M6  and Var5 = MAGH  and Var6 = DG
Var3 = M6  and Var5 = TURQ  and Var6 = DG
Var3 = M6  and Var5 = ARGE  and Var6 = DG
Var3 = M6  and Var5 = BRES  and Var6 = DG
Var3 = M6  and Var5 = CHIL  and Var6 = DG
Var3 = M6  and Var5 = COLO  and Var6 = DG
Var3 = M6  and Var5 = AFSU  and Var6 = DD
Var3 = M6  and Var5 = MARO  and Var6 = DG
Var3 = M6  and Var5 = ISRA  and Var6 = DG
Var3 = M6  and Var5 = HONG  and Var6 = DG
Var3 = M6  and Var5 = TCHE  and Var6 = DG
Var3 = M6  and Var5 = POLO  and Var6 = DG
Var3 = M6  and Var5 = SLVQ  and Var6 = DG
Var3 = M6  and Var5 = JAPO  and Var6 = DD
Var3 = M6  and Var5 = TAIW  and Var6 = DG
Var3 = M6  and Var5 = AUST  and Var6 = DD
Var3 = M6  and Var5 = URUG  and Var6 = DG
Var3 = M6  and Var5 = DAIB  and Var6 = DG
Var3 = M6  and Var5 = DAIC  and Var6 = DG
Var3 = M6  and Var5 = DAID  and Var6 = DD
Var3 = M6  and Var5 = DAIF  and Var6 = DG
Var3 = M6  and Var5 = EUOR  and Var6 = DG
Var3 = M6  and Var5 = CETI  and Var6 = DG
Var3 = M7  and Var5 = FRAN  and Var6 = DG
Var3 = M7  and Var5 = DOTO  and Var6 = DG
Var3 = M7  and Var5 = ALLE  and Var6 = DG
Var3 = M7  and Var5 = AUTR  and Var6 = DG
Var3 = M7  and Var5 = BELG  and Var6 = DG
Var3 = M7  and Var5 = DANE  and Var6 = DG
Var3 = M7  and Var5 = ESPA  and Var6 = DG
Var3 = M7  and Var5 = FINL  and Var6 = DG
Var3 = M7  and Var5 = GRBR  and Var6 = DD
Var3 = M7  and Var5 = GREC  and Var6 = DG
Var3 = M7  and Var5 = HOLL  and Var6 = DG
Var3 = M7  and Var5 = IRLA  and Var6 = DD
Var3 = M7  and Var5 = ISLA  and Var6 = DG
Var3 = M7  and Var5 = ITAL  and Var6 = DG
Var3 = M7  and Var5 = NORV  and Var6 = DG
Var3 = M7  and Var5 = PORT  and Var6 = DG
Var3 = M7  and Var5 = SUED  and Var6 = DG
Var3 = M7  and Var5 = SUIS  and Var6 = DG
Var3 = M7  and Var5 = YOUG  and Var6 = DG
Var3 = M7  and Var5 = MAGH  and Var6 = DG
Var3 = M7  and Var5 = TURQ  and Var6 = DG
Var3 = M7  and Var5 = ARGE  and Var6 = DG
Var3 = M7  and Var5 = BRES  and Var6 = DG
Var3 = M7  and Var5 = CHIL  and Var6 = DG
Var3 = M7  and Var5 = COLO  and Var6 = DG
Var3 = M7  and Var5 = AFSU  and Var6 = DD
Var3 = M7  and Var5 = MARO  and Var6 = DG
Var3 = M7  and Var5 = ISRA  and Var6 = DG
Var3 = M7  and Var5 = HONG  and Var6 = DG
Var3 = M7  and Var5 = TCHE  and Var6 = DG
Var3 = M7  and Var5 = POLO  and Var6 = DG
Var3 = M7  and Var5 = SLVQ  and Var6 = DG
Var3 = M7  and Var5 = JAPO  and Var6 = DD
Var3 = M7  and Var5 = TAIW  and Var6 = DG
Var3 = M7  and Var5 = AUST  and Var6 = DD
Var3 = M7  and Var5 = URUG  and Var6 = DG
Var3 = M7  and Var5 = DAIB  and Var6 = DG
Var3 = M7  and Var5 = DAIC  and Var6 = DG
Var3 = M7  and Var5 = DAID  and Var6 = DD
Var3 = M7  and Var5 = DAIF  and Var6 = DG
Var3 = M7  and Var5 = EUOR  and Var6 = DG
Var3 = M7  and Var5 = CETI  and Var6 = DG
Var3 = M8  and Var5 = FRAN  and Var6 = DG
Var3 = M8  and Var5 = DOTO  and Var6 = DG
Var3 = M8  and Var5 = ALLE  and Var6 = DG
Var3 = M8  and Var5 = AUTR  and Var6 = DG
Var3 = M8  and Var5 = BELG  and Var6 = DG
Var3 = M8  and Var5 = DANE  and Var6 = DG
Var3 = M8  and Var5 = ESPA  and Var6 = DG
Var3 = M8  and Var5 = FINL  and Var6 = DG
Var3 = M8  and Var5 = GRBR  and Var6 = DD
Var3 = M8  and Var5 = GREC  and Var6 = DG
Var3 = M8  and Var5 = HOLL  and Var6 = DG
Var3 = M8  and Var5 = IRLA  and Var6 = DD
Var3 = M8  and Var5 = ISLA  and Var6 = DG
Var3 = M8  and Var5 = ITAL  and Var6 = DG
Var3 = M8  and Var5 = NORV  and Var6 = DG
Var3 = M8  and Var5 = PORT  and Var6 = DG
Var3 = M8  and Var5 = SUED  and Var6 = DG
Var3 = M8  and Var5 = SUIS  and Var6 = DG
Var3 = M8  and Var5 = YOUG  and Var6 = DG
Var3 = M8  and Var5 = MAGH  and Var6 = DG
Var3 = M8  and Var5 = TURQ  and Var6 = DG
Var3 = M8  and Var5 = ARGE  and Var6 = DG
Var3 = M8  and Var5 = BRES  and Var6 = DG
Var3 = M8  and Var5 = CHIL  and Var6 = DG
Var3 = M8  and Var5 = COLO  and Var6 = DG
Var3 = M8  and Var5 = AFSU  and Var6 = DD
Var3 = M8  and Var5 = MARO  and Var6 = DG
Var3 = M8  and Var5 = ISRA  and Var6 = DG
Var3 = M8  and Var5 = HONG  and Var6 = DG
Var3 = M8  and Var5 = TCHE  and Var6 = DG
Var3 = M8  and Var5 = POLO  and Var6 = DG
Var3 = M8  and Var5 = SLVQ  and Var6 = DG
Var3 = M8  and Var5 = JAPO  and Var6 = DD
Var3 = M8  and Var5 = TAIW  and Var6 = DG
Var3 = M8  and Var5 = AUST  and Var6 = DD
Var3 = M8  and Var5 = URUG  and Var6 = DG
Var3 = M8  and Var5 = DAIB  and Var6 = DG
Var3 = M8  and Var5 = DAIC  and Var6 = DG
Var3 = M8  and Var5 = DAID  and Var6 = DD
Var3 = M8  and Var5 = DAIF  and Var6 = DG
Var3 = M8  and Var5 = EUOR  and Var6 = DG
Var3 = M8  and Var5 = CETI  and Var6 = DG
Var3 = M9  and Var5 = FRAN  and Var6 = DG
Var3 = M9  and Var5 = DOTO  and Var6 = DG
Var3 = M9  and Var5 = ALLE  and Var6 = DG
Var3 = M9  and Var5 = AUTR  and Var6 = DG
Var3 = M9  and Var5 = BELG  and Var6 = DG
Var3 = M9  and Var5 = DANE  and Var6 = DG
Var3 = M9  and Var5 = ESPA  and Var6 = DG
Var3 = M9  and Var5 = FINL  and Var6 = DG
Var3 = M9  and Var5 = GRBR  and Var6 = DD
Var3 = M9  and Var5 = GREC  and Var6 = DG
Var3 = M9  and Var5 = HOLL  and Var6 = DG
Var3 = M9  and Var5 = IRLA  and Var6 = DD
Var3 = M9  and Var5 = ISLA  and Var6 = DG
Var3 = M9  and Var5 = ITAL  and Var6 = DG
Var3 = M9  and Var5 = NORV  and Var6 = DG
Var3 = M9  and Var5 = PORT  and Var6 = DG
Var3 = M9  and Var5 = SUED  and Var6 = DG
Var3 = M9  and Var5 = SUIS  and Var6 = DG
Var3 = M9  and Var5 = YOUG  and Var6 = DG
Var3 = M9  and Var5 = MAGH  and Var6 = DG
Var3 = M9  and Var5 = TURQ  and Var6 = DG
Var3 = M9  and Var5 = ARGE  and Var6 = DG
Var3 = M9  and Var5 = BRES  and Var6 = DG
Var3 = M9  and Var5 = CHIL  and Var6 = DG
Var3 = M9  and Var5 = COLO  and Var6 = DG
Var3 = M9  and Var5 = AFSU  and Var6 = DD
Var3 = M9  and Var5 = MARO  and Var6 = DG
Var3 = M9  and Var5 = ISRA  and Var6 = DG
Var3 = M9  and Var5 = HONG  and Var6 = DG
Var3 = M9  and Var5 = TCHE  and Var6 = DG
Var3 = M9  and Var5 = POLO  and Var6 = DG
Var3 = M9  and Var5 = SLVQ  and Var6 = DG
Var3 = M9  and Var5 = JAPO  and Var6 = DD
Var3 = M9  and Var5 = TAIW  and Var6 = DG
Var3 = M9  and Var5 = AUST  and Var6 = DD
Var3 = M9  and Var5 = URUG  and Var6 = DG
Var3 = M9  and Var5 = DAIB  and Var6 = DG
Var3 = M9  and Var5 = DAIC  and Var6 = DG
Var3 = M9  and Var5 = DAID  and Var6 = DD
Var3 = M9  and Var5 = DAIF  and Var6 = DG
Var3 = M9  and Var5 = EUOR  and Var6 = DG
Var3 = M9  and Var5 = CETI  and Var6 = DG
Var3 = MA  and Var5 = FRAN  and Var6 = DG
Var3 = MA  and Var5 = DOTO  and Var6 = DG
Var3 = MA  and Var5 = ALLE  and Var6 = DG
Var3 = MA  and Var5 = AUTR  and Var6 = DG
Var3 = MA  and Var5 = BELG  and Var6 = DG
Var3 = MA  and Var5 = DANE  and Var6 = DG
Var3 = MA  and Var5 = ESPA  and Var6 = DG
Var3 = MA  and Var5 = FINL  and Var6 = DG
Var3 = MA  and Var5 = GRBR  and Var6 = DD
Var3 = MA  and Var5 = GREC  and Var6 = DG
Var3 = MA  and Var5 = HOLL  and Var6 = DG
Var3 = MA  and Var5 = IRLA  and Var6 = DD
Var3 = MA  and Var5 = ISLA  and Var6 = DG
Var3 = MA  and Var5 = ITAL  and Var6 = DG
Var3 = MA  and Var5 = NORV  and Var6 = DG
Var3 = MA  and Var5 = PORT  and Var6 = DG
Var3 = MA  and Var5 = SUED  and Var6 = DG
Var3 = MA  and Var5 = SUIS  and Var6 = DG
Var3 = MA  and Var5 = YOUG  and Var6 = DG
Var3 = MA  and Var5 = MAGH  and Var6 = DG
Var3 = MA  and Var5 = TURQ  and Var6 = DG
Var3 = MA  and Var5 = ARGE  and Var6 = DG
Var3 = MA  and Var5 = BRES  and Var6 = DG
Var3 = MA  and Var5 = CHIL  and Var6 = DG
Var3 = MA  and Var5 = COLO  and Var6 = DG
Var3 = MA  and Var5 = AFSU  and Var6 = DD
Var3 = MA  and Var5 = MARO  and Var6 = DG
Var3 = MA  and Var5 = ISRA  and Var6 = DG
Var3 = MA  and Var5 = HONG  and Var6 = DG
Var3 = MA  and Var5 = TCHE  and Var6 = DG
Var3 = MA  and Var5 = POLO  and Var6 = DG
Var3 = MA  and Var5 = SLVQ  and Var6 = DG
Var3 = MA  and Var5 = JAPO  and Var6 = DD
Var3 = MA  and Var5 = TAIW  and Var6 = DG
Var3 = MA  and Var5 = AUST  and Var6 = DD
Var3 = MA  and Var5 = URUG  and Var6 = DG
Var3 = MA  and Var5 = DAIB  and Var6 = DG
Var3 = MA  and Var5 = DAIC  and Var6 = DG
Var3 = MA  and Var5 = DAID  and Var6 = DD
Var3 = MA  and Var5 = DAIF  and Var6 = DG
Var3 = MA  and Var5 = EUOR  and Var6 = DG
Var3 = MA  and Var5 = CETI  and Var6 = DG
Var3 = MB  and Var5 = FRAN  and Var6 = DG
Var3 = MB  and Var5 = DOTO  and Var6 = DG
Var3 = MB  and Var5 = ALLE  and Var6 = DG
Var3 = MB  and Var5 = AUTR  and Var6 = DG
Var3 = MB  and Var5 = BELG  and Var6 = DG
Var3 = MB  and Var5 = DANE  and Var6 = DG
Var3 = MB  and Var5 = ESPA  and Var6 = DG
Var3 = MB  and Var5 = FINL  and Var6 = DG
Var3 = MB  and Var5 = GRBR  and Var6 = DD
Var3 = MB  and Var5 = GREC  and Var6 = DG
Var3 = MB  and Var5 = HOLL  and Var6 = DG
Var3 = MB  and Var5 = IRLA  and Var6 = DD
Var3 = MB  and Var5 = ISLA  and Var6 = DG
Var3 = MB  and Var5 = ITAL  and Var6 = DG
Var3 = MB  and Var5 = NORV  and Var6 = DG
Var3 = MB  and Var5 = PORT  and Var6 = DG
Var3 = MB  and Var5 = SUED  and Var6 = DG
Var3 = MB  and Var5 = SUIS  and Var6 = DG
Var3 = MB  and Var5 = YOUG  and Var6 = DG
Var3 = MB  and Var5 = MAGH  and Var6 = DG
Var3 = MB  and Var5 = TURQ  and Var6 = DG
Var3 = MB  and Var5 = ARGE  and Var6 = DG
Var3 = MB  and Var5 = BRES  and Var6 = DG
Var3 = MB  and Var5 = CHIL  and Var6 = DG
Var3 = MB  and Var5 = COLO  and Var6 = DG
Var3 = MB  and Var5 = AFSU  and Var6 = DD
Var3 = MB  and Var5 = MARO  and Var6 = DG
Var3 = MB  and Var5 = ISRA  and Var6 = DG
Var3 = MB  and Var5 = HONG  and Var6 = DG
Var3 = MB  and Var5 = TCHE  and Var6 = DG
Var3 = MB  and Var5 = POLO  and Var6 = DG
Var3 = MB  and Var5 = SLVQ  and Var6 = DG
Var3 = MB  and Var5 = JAPO  and Var6 = DD
Var3 = MB  and Var5 = TAIW  and Var6 = DG
Var3 = MB  and Var5 = AUST  and Var6 = DD
Var3 = MB  and Var5 = URUG  and Var6 = DG
Var3 = MB  and Var5 = DAIB  and Var6 = DG
Var3 = MB  and Var5 = DAIC  and Var6 = DG
Var3 = MB  and Var5 = DAID  and Var6 = DD
Var3 = MB  and Var5 = DAIF  and Var6 = DG
Var3 = MB  and Var5 = EUOR  and Var6 = DG
Var3 = MB  and Var5 = CETI  and Var6 = DG
Var3 = MC  and Var5 = FRAN  and Var6 = DG
Var3 = MC  and Var5 = DOTO  and Var6 = DG
Var3 = MC  and Var5 = ALLE  and Var6 = DG
Var3 = MC  and Var5 = AUTR  and Var6 = DG
Var3 = MC  and Var5 = BELG  and Var6 = DG
Var3 = MC  and Var5 = DANE  and Var6 = DG
Var3 = MC  and Var5 = ESPA  and Var6 = DG
Var3 = MC  and Var5 = FINL  and Var6 = DG
Var3 = MC  and Var5 = GRBR  and Var6 = DD
Var3 = MC  and Var5 = GREC  and Var6 = DG
Var3 = MC  and Var5 = HOLL  and Var6 = DG
Var3 = MC  and Var5 = IRLA  and Var6 = DD
Var3 = MC  and Var5 = ISLA  and Var6 = DG
Var3 = MC  and Var5 = ITAL  and Var6 = DG
Var3 = MC  and Var5 = NORV  and Var6 = DG
Var3 = MC  and Var5 = PORT  and Var6 = DG
Var3 = MC  and Var5 = SUED  and Var6 = DG
Var3 = MC  and Var5 = SUIS  and Var6 = DG
Var3 = MC  and Var5 = YOUG  and Var6 = DG
Var3 = MC  and Var5 = MAGH  and Var6 = DG
Var3 = MC  and Var5 = TURQ  and Var6 = DG
Var3 = MC  and Var5 = ARGE  and Var6 = DG
Var3 = MC  and Var5 = BRES  and Var6 = DG
Var3 = MC  and Var5 = CHIL  and Var6 = DG
Var3 = MC  and Var5 = COLO  and Var6 = DG
Var3 = MC  and Var5 = AFSU  and Var6 = DD
Var3 = MC  and Var5 = MARO  and Var6 = DG
Var3 = MC  and Var5 = ISRA  and Var6 = DG
Var3 = MC  and Var5 = HONG  and Var6 = DG
Var3 = MC  and Var5 = TCHE  and Var6 = DG
Var3 = MC  and Var5 = POLO  and Var6 = DG
Var3 = MC  and Var5 = SLVQ  and Var6 = DG
Var3 = MC  and Var5 = JAPO  and Var6 = DD
Var3 = MC  and Var5 = TAIW  and Var6 = DG
Var3 = MC  and Var5 = AUST  and Var6 = DD
Var3 = MC  and Var5 = URUG  and Var6 = DG
Var3 = MC  and Var5 = DAIB  and Var6 = DG
Var3 = MC  and Var5 = DAIC  and Var6 = DG
Var3 = MC  and Var5 = DAID  and Var6 = DD
Var3 = MC  and Var5 = DAIF  and Var6 = DG
Var3 = MC  and Var5 = EUOR  and Var6 = DG
Var3 = MC  and Var5 = CETI  and Var6 = DG
Var3 = MD  and Var5 = FRAN  and Var6 = DG
Var3 = MD  and Var5 = DOTO  and Var6 = DG
Var3 = MD  and Var5 = ALLE  and Var6 = DG
Var3 = MD  and Var5 = AUTR  and Var6 = DG
Var3 = MD  and Var5 = BELG  and Var6 = DG
Var3 = MD  and Var5 = DANE  and Var6 = DG
Var3 = MD  and Var5 = ESPA  and Var6 = DG
Var3 = MD  and Var5 = FINL  and Var6 = DG
Var3 = MD  and Var5 = GRBR  and Var6 = DD
Var3 = MD  and Var5 = GREC  and Var6 = DG
Var3 = MD  and Var5 = HOLL  and Var6 = DG
Var3 = MD  and Var5 = IRLA  and Var6 = DD
Var3 = MD  and Var5 = ISLA  and Var6 = DG
Var3 = MD  and Var5 = ITAL  and Var6 = DG
Var3 = MD  and Var5 = NORV  and Var6 = DG
Var3 = MD  and Var5 = PORT  and Var6 = DG
Var3 = MD  and Var5 = SUED  and Var6 = DG
Var3 = MD  and Var5 = SUIS  and Var6 = DG
Var3 = MD  and Var5 = YOUG  and Var6 = DG
Var3 = MD  and Var5 = MAGH  and Var6 = DG
Var3 = MD  and Var5 = TURQ  and Var6 = DG
Var3 = MD  and Var5 = ARGE  and Var6 = DG
Var3 = MD  and Var5 = BRES  and Var6 = DG
Var3 = MD  and Var5 = CHIL  and Var6 = DG
Var3 = MD  and Var5 = COLO  and Var6 = DG
Var3 = MD  and Var5 = AFSU  and Var6 = DD
Var3 = MD  and Var5 = MARO  and Var6 = DG
Var3 = MD  and Var5 = ISRA  and Var6 = DG
Var3 = MD  and Var5 = HONG  and Var6 = DG
Var3 = MD  and Var5 = TCHE  and Var6 = DG
Var3 = MD  and Var5 = POLO  and Var6 = DG
Var3 = MD  and Var5 = SLVQ  and Var6 = DG
Var3 = MD  and Var5 = JAPO  and Var6 = DD
Var3 = MD  and Var5 = TAIW  and Var6 = DG
Var3 = MD  and Var5 = AUST  and Var6 = DD
Var3 = MD  and Var5 = URUG  and Var6 = DG
Var3 = MD  and Var5 = DAIB  and Var6 = DG
Var3 = MD  and Var5 = DAIC  and Var6 = DG
Var3 = MD  and Var5 = DAID  and Var6 = DD
Var3 = MD  and Var5 = DAIF  and Var6 = DG
Var3 = MD  and Var5 = EUOR  and Var6 = DG
Var3 = MD  and Var5 = CETI  and Var6 = DG
Var3 = ME  and Var5 = FRAN  and Var6 = DG
Var3 = ME  and Var5 = DOTO  and Var6 = DG
Var3 = ME  and Var5 = ALLE  and Var6 = DG
Var3 = ME  and Var5 = AUTR  and Var6 = DG
Var3 = ME  and Var5 = BELG  and Var6 = DG
Var3 = ME  and Var5 = DANE  and Var6 = DG
Var3 = ME  and Var5 = ESPA  and Var6 = DG
Var3 = ME  and Var5 = FINL  and Var6 = DG
Var3 = ME  and Var5 = GRBR  and Var6 = DD
Var3 = ME  and Var5 = GREC  and Var6 = DG
Var3 = ME  and Var5 = HOLL  and Var6 = DG
Var3 = ME  and Var5 = IRLA  and Var6 = DD
Var3 = ME  and Var5 = ISLA  and Var6 = DG
Var3 = ME  and Var5 = ITAL  and Var6 = DG
Var3 = ME  and Var5 = NORV  and Var6 = DG
Var3 = ME  and Var5 = PORT  and Var6 = DG
Var3 = ME  and Var5 = SUED  and Var6 = DG
Var3 = ME  and Var5 = SUIS  and Var6 = DG
Var3 = ME  and Var5 = YOUG  and Var6 = DG
Var3 = ME  and Var5 = MAGH  and Var6 = DG
Var3 = ME  and Var5 = TURQ  and Var6 = DG
Var3 = ME  and Var5 = ARGE  and Var6 = DG
Var3 = ME  and Var5 = BRES  and Var6 = DG
Var3 = ME  and Var5 = CHIL  and Var6 = DG
Var3 = ME  and Var5 = COLO  and Var6 = DG
Var3 = ME  and Var5 = AFSU  and Var6 = DD
Var3 = ME  and Var5 = MARO  and Var6 = DG
Var3 = ME  and Var5 = ISRA  and Var6 = DG
Var3 = ME  and Var5 = HONG  and Var6 = DG
Var3 = ME  and Var5 = TCHE  and Var6 = DG
Var3 = ME  and Var5 = POLO  and Var6 = DG
Var3 = ME  and Var5 = SLVQ  and Var6 = DG
Var3 = ME  and Var5 = JAPO  and Var6 = DD
Var3 = ME  and Var5 = TAIW  and Var6 = DG
Var3 = ME  and Var5 = AUST  and Var6 = DD
Var3 = ME  and Var5 = URUG  and Var6 = DG
Var3 = ME  and Var5 = DAIB  and Var6 = DG
Var3 = ME  and Var5 = DAIC  and Var6 = DG
Var3 = ME  and Var5 = DAID  and Var6 = DD
Var3 = ME  and Var5 = DAIF  and Var6 = DG
Var3 = ME  and Var5 = EUOR  and Var6 = DG
Var3 = ME  and Var5 = CETI  and Var6 = DG
Var3 = MF  and Var5 = FRAN  and Var6 = DG
Var3 = MF  and Var5 = DOTO  and Var6 = DG
Var3 = MF  and Var5 = ALLE  and Var6 = DG
Var3 = MF  and Var5 = AUTR  and Var6 = DG
Var3 = MF  and Var5 = BELG  and Var6 = DG
Var3 = MF  and Var5 = DANE  and Var6 = DG
Var3 = MF  and Var5 = ESPA  and Var6 = DG
Var3 = MF  and Var5 = FINL  and Var6 = DG
Var3 = MF  and Var5 = GRBR  and Var6 = DD
Var3 = MF  and Var5 = GREC  and Var6 = DG
Var3 = MF  and Var5 = HOLL  and Var6 = DG
Var3 = MF  and Var5 = IRLA  and Var6 = DD
Var3 = MF  and Var5 = ISLA  and Var6 = DG
Var3 = MF  and Var5 = ITAL  and Var6 = DG
Var3 = MF  and Var5 = NORV  and Var6 = DG
Var3 = MF  and Var5 = PORT  and Var6 = DG
Var3 = MF  and Var5 = SUED  and Var6 = DG
Var3 = MF  and Var5 = SUIS  and Var6 = DG
Var3 = MF  and Var5 = YOUG  and Var6 = DG
Var3 = MF  and Var5 = MAGH  and Var6 = DG
Var3 = MF  and Var5 = TURQ  and Var6 = DG
Var3 = MF  and Var5 = ARGE  and Var6 = DG
Var3 = MF  and Var5 = BRES  and Var6 = DG
Var3 = MF  and Var5 = CHIL  and Var6 = DG
Var3 = MF  and Var5 = COLO  and Var6 = DG
Var3 = MF  and Var5 = AFSU  and Var6 = DD
Var3 = MF  and Var5 = MARO  and Var6 = DG
Var3 = MF  and Var5 = ISRA  and Var6 = DG
Var3 = MF  and Var5 = HONG  and Var6 = DG
Var3 = MF  and Var5 = TCHE  and Var6 = DG
Var3 = MF  and Var5 = POLO  and Var6 = DG
Var3 = MF  and Var5 = SLVQ  and Var6 = DG
Var3 = MF  and Var5 = JAPO  and Var6 = DD
Var3 = MF  and Var5 = TAIW  and Var6 = DG
Var3 = MF  and Var5 = AUST  and Var6 = DD
Var3 = MF  and Var5 = URUG  and Var6 = DG
Var3 = MF  and Var5 = DAIB  and Var6 = DG
Var3 = MF  and Var5 = DAIC  and Var6 = DG
Var3 = MF  and Var5 = DAID  and Var6 = DD
Var3 = MF  and Var5 = DAIF  and Var6 = DG
Var3 = MF  and Var5 = EUOR  and Var6 = DG
Var3 = MF  and Var5 = CETI  and Var6 = DG
Var3 = MJ  and Var5 = FRAN  and Var6 = DG
Var3 = MJ  and Var5 = DOTO  and Var6 = DG
Var3 = MJ  and Var5 = ALLE  and Var6 = DG
Var3 = MJ  and Var5 = AUTR  and Var6 = DG
Var3 = MJ  and Var5 = BELG  and Var6 = DG
Var3 = MJ  and Var5 = DANE  and Var6 = DG
Var3 = MJ  and Var5 = ESPA  and Var6 = DG
Var3 = MJ  and Var5 = FINL  and Var6 = DG
Var3 = MJ  and Var5 = GRBR  and Var6 = DD
Var3 = MJ  and Var5 = GREC  and Var6 = DG
Var3 = MJ  and Var5 = HOLL  and Var6 = DG
Var3 = MJ  and Var5 = IRLA  and Var6 = DD
Var3 = MJ  and Var5 = ISLA  and Var6 = DG
Var3 = MJ  and Var5 = ITAL  and Var6 = DG
Var3 = MJ  and Var5 = NORV  and Var6 = DG
Var3 = MJ  and Var5 = PORT  and Var6 = DG
Var3 = MJ  and Var5 = SUED  and Var6 = DG
Var3 = MJ  and Var5 = SUIS  and Var6 = DG
Var3 = MJ  and Var5 = YOUG  and Var6 = DG
Var3 = MJ  and Var5 = MAGH  and Var6 = DG
Var3 = MJ  and Var5 = TURQ  and Var6 = DG
Var3 = MJ  and Var5 = ARGE  and Var6 = DG
Var3 = MJ  and Var5 = BRES  and Var6 = DG
Var3 = MJ  and Var5 = CHIL  and Var6 = DG
Var3 = MJ  and Var5 = COLO  and Var6 = DG
Var3 = MJ  and Var5 = AFSU  and Var6 = DD
Var3 = MJ  and Var5 = MARO  and Var6 = DG
Var3 = MJ  and Var5 = ISRA  and Var6 = DG
Var3 = MJ  and Var5 = HONG  and Var6 = DG
Var3 = MJ  and Var5 = TCHE  and Var6 = DG
Var3 = MJ  and Var5 = POLO  and Var6 = DG
Var3 = MJ  and Var5 = SLVQ  and Var6 = DG
Var3 = MJ  and Var5 = JAPO  and Var6 = DD
Var3 = MJ  and Var5 = TAIW  and Var6 = DG
Var3 = MJ  and Var5 = AUST  and Var6 = DD
Var3 = MJ  and Var5 = URUG  and Var6 = DG
Var3 = MJ  and Var5 = DAIB  and Var6 = DG
Var3 = MJ  and Var5 = DAIC  and Var6 = DG
Var3 = MJ  and Var5 = DAID  and Var6 = DD
Var3 = MJ  and Var5 = DAIF  and Var6 = DG
Var3 = MJ  and Var5 = EUOR  and Var6 = DG
Var3 = MJ  and Var5 = CETI  and Var6 = DG
Var3 = MK  and Var5 = FRAN  and Var6 = DG
Var3 = MK  and Var5 = DOTO  and Var6 = DG
Var3 = MK  and Var5 = ALLE  and Var6 = DG
Var3 = MK  and Var5 = AUTR  and Var6 = DG
Var3 = MK  and Var5 = BELG  and Var6 = DG
Var3 = MK  and Var5 = DANE  and Var6 = DG
Var3 = MK  and Var5 = ESPA  and Var6 = DG
Var3 = MK  and Var5 = FINL  and Var6 = DG
Var3 = MK  and Var5 = GRBR  and Var6 = DD
Var3 = MK  and Var5 = GREC  and Var6 = DG
Var3 = MK  and Var5 = HOLL  and Var6 = DG
Var3 = MK  and Var5 = IRLA  and Var6 = DD
Var3 = MK  and Var5 = ISLA  and Var6 = DG
Var3 = MK  and Var5 = ITAL  and Var6 = DG
Var3 = MK  and Var5 = NORV  and Var6 = DG
Var3 = MK  and Var5 = PORT  and Var6 = DG
Var3 = MK  and Var5 = SUED  and Var6 = DG
Var3 = MK  and Var5 = SUIS  and Var6 = DG
Var3 = MK  and Var5 = YOUG  and Var6 = DG
Var3 = MK  and Var5 = MAGH  and Var6 = DG
Var3 = MK  and Var5 = TURQ  and Var6 = DG
Var3 = MK  and Var5 = ARGE  and Var6 = DG
Var3 = MK  and Var5 = BRES  and Var6 = DG
Var3 = MK  and Var5 = CHIL  and Var6 = DG
Var3 = MK  and Var5 = COLO  and Var6 = DG
Var3 = MK  and Var5 = AFSU  and Var6 = DD
Var3 = MK  and Var5 = MARO  and Var6 = DG
Var3 = MK  and Var5 = ISRA  and Var6 = DG
Var3 = MK  and Var5 = HONG  and Var6 = DG
Var3 = MK  and Var5 = TCHE  and Var6 = DG
Var3 = MK  and Var5 = POLO  and Var6 = DG
Var3 = MK  and Var5 = SLVQ  and Var6 = DG
Var3 = MK  and Var5 = JAPO  and Var6 = DD
Var3 = MK  and Var5 = TAIW  and Var6 = DG
Var3 = MK  and Var5 = AUST  and Var6 = DD
Var3 = MK  and Var5 = URUG  and Var6 = DG
Var3 = MK  and Var5 = DAIB  and Var6 = DG
Var3 = MK  and Var5 = DAIC  and Var6 = DG
Var3 = MK  and Var5 = DAID  and Var6 = DD
Var3 = MK  and Var5 = DAIF  and Var6 = DG
Var3 = MK  and Var5 = EUOR  and Var6 = DG
Var3 = MK  and Var5 = CETI  and Var6 = DG
Var3 = ML  and Var5 = FRAN  and Var6 = DG
Var3 = ML  and Var5 = DOTO  and Var6 = DG
Var3 = ML  and Var5 = ALLE  and Var6 = DG
Var3 = ML  and Var5 = AUTR  and Var6 = DG
Var3 = ML  and Var5 = BELG  and Var6 = DG
Var3 = ML  and Var5 = DANE  and Var6 = DG
Var3 = ML  and Var5 = ESPA  and Var6 = DG
Var3 = ML  and Var5 = FINL  and Var6 = DG
Var3 = ML  and Var5 = GRBR  and Var6 = DD
Var3 = ML  and Var5 = GREC  and Var6 = DG
Var3 = ML  and Var5 = HOLL  and Var6 = DG
Var3 = ML  and Var5 = IRLA  and Var6 = DD
Var3 = ML  and Var5 = ISLA  and Var6 = DG
Var3 = ML  and Var5 = ITAL  and Var6 = DG
Var3 = ML  and Var5 = NORV  and Var6 = DG
Var3 = ML  and Var5 = PORT  and Var6 = DG
Var3 = ML  and Var5 = SUED  and Var6 = DG
Var3 = ML  and Var5 = SUIS  and Var6 = DG
Var3 = ML  and Var5 = YOUG  and Var6 = DG
Var3 = ML  and Var5 = MAGH  and Var6 = DG
Var3 = ML  and Var5 = TURQ  and Var6 = DG
Var3 = ML  and Var5 = ARGE  and Var6 = DG
Var3 = ML  and Var5 = BRES  and Var6 = DG
Var3 = ML  and Var5 = CHIL  and Var6 = DG
Var3 = ML  and Var5 = COLO  and Var6 = DG
Var3 = ML  and Var5 = AFSU  and Var6 = DD
Var3 = ML  and Var5 = MARO  and Var6 = DG
Var3 = ML  and Var5 = ISRA  and Var6 = DG
Var3 = ML  and Var5 = HONG  and Var6 = DG
Var3 = ML  and Var5 = TCHE  and Var6 = DG
Var3 = ML  and Var5 = POLO  and Var6 = DG
Var3 = ML  and Var5 = SLVQ  and Var6 = DG
Var3 = ML  and Var5 = JAPO  and Var6 = DD
Var3 = ML  and Var5 = TAIW  and Var6 = DG
Var3 = ML  and Var5 = AUST  and Var6 = DD
Var3 = ML  and Var5 = URUG  and Var6 = DG
Var3 = ML  and Var5 = DAIB  and Var6 = DG
Var3 = ML  and Var5 = DAIC  and Var6 = DG
Var3 = ML  and Var5 = DAID  and Var6 = DD
Var3 = ML  and Var5 = DAIF  and Var6 = DG
Var3 = ML  and Var5 = EUOR  and Var6 = DG
Var3 = ML  and Var5 = CETI  and Var6 = DG
Var3 = MM  and Var5 = FRAN  and Var6 = DG
Var3 = MM  and Var5 = DOTO  and Var6 = DG
Var3 = MM  and Var5 = ALLE  and Var6 = DG
Var3 = MM  and Var5 = AUTR  and Var6 = DG
Var3 = MM  and Var5 = BELG  and Var6 = DG
Var3 = MM  and Var5 = DANE  and Var6 = DG
Var3 = MM  and Var5 = ESPA  and Var6 = DG
Var3 = MM  and Var5 = FINL  and Var6 = DG
Var3 = MM  and Var5 = GRBR  and Var6 = DD
Var3 = MM  and Var5 = GREC  and Var6 = DG
Var3 = MM  and Var5 = HOLL  and Var6 = DG
Var3 = MM  and Var5 = IRLA  and Var6 = DD
Var3 = MM  and Var5 = ISLA  and Var6 = DG
Var3 = MM  and Var5 = ITAL  and Var6 = DG
Var3 = MM  and Var5 = NORV  and Var6 = DG
Var3 = MM  and Var5 = PORT  and Var6 = DG
Var3 = MM  and Var5 = SUED  and Var6 = DG
Var3 = MM  and Var5 = SUIS  and Var6 = DG
Var3 = MM  and Var5 = YOUG  and Var6 = DG
Var3 = MM  and Var5 = MAGH  and Var6 = DG
Var3 = MM  and Var5 = TURQ  and Var6 = DG
Var3 = MM  and Var5 = ARGE  and Var6 = DG
Var3 = MM  and Var5 = BRES  and Var6 = DG
Var3 = MM  and Var5 = CHIL  and Var6 = DG
Var3 = MM  and Var5 = COLO  and Var6 = DG
Var3 = MM  and Var5 = AFSU  and Var6 = DD
Var3 = MM  and Var5 = MARO  and Var6 = DG
Var3 = MM  and Var5 = ISRA  and Var6 = DG
Var3 = MM  and Var5 = HONG  and Var6 = DG
Var3 = MM  and Var5 = TCHE  and Var6 = DG
Var3 = MM  and Var5 = POLO  and Var6 = DG
Var3 = MM  and Var5 = SLVQ  and Var6 = DG
Var3 = MM  and Var5 = JAPO  and Var6 = DD
Var3 = MM  and Var5 = TAIW  and Var6 = DG
Var3 = MM  and Var5 = AUST  and Var6 = DD
Var3 = MM  and Var5 = URUG  and Var6 = DG
Var3 = MM  and Var5 = DAIB  and Var6 = DG
Var3 = MM  and Var5 = DAIC  and Var6 = DG
Var3 = MM  and Var5 = DAID  and Var6 = DD
Var3 = MM  and Var5 = DAIF  and Var6 = DG
Var3 = MM  and Var5 = EUOR  and Var6 = DG
Var3 = MM  and Var5 = CETI  and Var6 = DG
Var3 = MS  and Var5 = FRAN  and Var6 = DG
Var3 = MS  and Var5 = DOTO  and Var6 = DG
Var3 = MS  and Var5 = ALLE  and Var6 = DG
Var3 = MS  and Var5 = AUTR  and Var6 = DG
Var3 = MS  and Var5 = BELG  and Var6 = DG
Var3 = MS  and Var5 = DANE  and Var6 = DG
Var3 = MS  and Var5 = ESPA  and Var6 = DG
Var3 = MS  and Var5 = FINL  and Var6 = DG
Var3 = MS  and Var5 = GRBR  and Var6 = DD
Var3 = MS  and Var5 = GREC  and Var6 = DG
Var3 = MS  and Var5 = HOLL  and Var6 = DG
Var3 = MS  and Var5 = IRLA  and Var6 = DD
Var3 = MS  and Var5 = ISLA  and Var6 = DG
Var3 = MS  and Var5 = ITAL  and Var6 = DG
Var3 = MS  and Var5 = NORV  and Var6 = DG
Var3 = MS  and Var5 = PORT  and Var6 = DG
Var3 = MS  and Var5 = SUED  and Var6 = DG
Var3 = MS  and Var5 = SUIS  and Var6 = DG
Var3 = MS  and Var5 = YOUG  and Var6 = DG
Var3 = MS  and Var5 = MAGH  and Var6 = DG
Var3 = MS  and Var5 = TURQ  and Var6 = DG
Var3 = MS  and Var5 = ARGE  and Var6 = DG
Var3 = MS  and Var5 = BRES  and Var6 = DG
Var3 = MS  and Var5 = CHIL  and Var6 = DG
Var3 = MS  and Var5 = COLO  and Var6 = DG
Var3 = MS  and Var5 = AFSU  and Var6 = DD
Var3 = MS  and Var5 = MARO  and Var6 = DG
Var3 = MS  and Var5 = ISRA  and Var6 = DG
Var3 = MS  and Var5 = HONG  and Var6 = DG
Var3 = MS  and Var5 = TCHE  and Var6 = DG
Var3 = MS  and Var5 = POLO  and Var6 = DG
Var3 = MS  and Var5 = SLVQ  and Var6 = DG
Var3 = MS  and Var5 = JAPO  and Var6 = DD
Var3 = MS  and Var5 = TAIW  and Var6 = DG
Var3 = MS  and Var5 = AUST  and Var6 = DD
Var3 = MS  and Var5 = URUG  and Var6 = DG
Var3 = MS  and Var5 = DAIB  and Var6 = DG
Var3 = MS  and Var5 = DAIC  and Var6 = DG
Var3 = MS  and Var5 = DAID  and Var6 = DD
Var3 = MS  and Var5 = DAIF  and Var6 = DG
Var3 = MS  and Var5 = EUOR  and Var6 = DG
Var3 = MS  and Var5 = CETI  and Var6 = DG
Var3 = MT  and Var5 = FRAN  and Var6 = DG
Var3 = MT  and Var5 = DOTO  and Var6 = DG
Var3 = MT  and Var5 = ALLE  and Var6 = DG
Var3 = MT  and Var5 = AUTR  and Var6 = DG
Var3 = MT  and Var5 = BELG  and Var6 = DG
Var3 = MT  and Var5 = DANE  and Var6 = DG
Var3 = MT  and Var5 = ESPA  and Var6 = DG
Var3 = MT  and Var5 = FINL  and Var6 = DG
Var3 = MT  and Var5 = GRBR  and Var6 = DD
Var3 = MT  and Var5 = GREC  and Var6 = DG
Var3 = MT  and Var5 = HOLL  and Var6 = DG
Var3 = MT  and Var5 = IRLA  and Var6 = DD
Var3 = MT  and Var5 = ISLA  and Var6 = DG
Var3 = MT  and Var5 = ITAL  and Var6 = DG
Var3 = MT  and Var5 = NORV  and Var6 = DG
Var3 = MT  and Var5 = PORT  and Var6 = DG
Var3 = MT  and Var5 = SUED  and Var6 = DG
Var3 = MT  and Var5 = SUIS  and Var6 = DG
Var3 = MT  and Var5 = YOUG  and Var6 = DG
Var3 = MT  and Var5 = MAGH  and Var6 = DG
Var3 = MT  and Var5 = TURQ  and Var6 = DG
Var3 = MT  and Var5 = ARGE  and Var6 = DG
Var3 = MT  and Var5 = BRES  and Var6 = DG
Var3 = MT  and Var5 = CHIL  and Var6 = DG
Var3 = MT  and Var5 = COLO  and Var6 = DG
Var3 = MT  and Var5 = AFSU  and Var6 = DD
Var3 = MT  and Var5 = MARO  and Var6 = DG
Var3 = MT  and Var5 = ISRA  and Var6 = DG
Var3 = MT  and Var5 = HONG  and Var6 = DG
Var3 = MT  and Var5 = TCHE  and Var6 = DG
Var3 = MT  and Var5 = POLO  and Var6 = DG
Var3 = MT  and Var5 = SLVQ  and Var6 = DG
Var3 = MT  and Var5 = JAPO  and Var6 = DD
Var3 = MT  and Var5 = TAIW  and Var6 = DG
Var3 = MT  and Var5 = AUST  and Var6 = DD
Var3 = MT  and Var5 = URUG  and Var6 = DG
Var3 = MT  and Var5 = DAIB  and Var6 = DG
Var3 = MT  and Var5 = DAIC  and Var6 = DG
Var3 = MT  and Var5 = DAID  and Var6 = DD
Var3 = MT  and Var5 = DAIF  and Var6 = DG
Var3 = MT  and Var5 = EUOR  and Var6 = DG
Var3 = MT  and Var5 = CETI  and Var6 = DG
Var3 = MU  and Var5 = FRAN  and Var6 = DG
Var3 = MU  and Var5 = DOTO  and Var6 = DG
Var3 = MU  and Var5 = ALLE  and Var6 = DG
Var3 = MU  and Var5 = AUTR  and Var6 = DG
Var3 = MU  and Var5 = BELG  and Var6 = DG
Var3 = MU  and Var5 = DANE  and Var6 = DG
Var3 = MU  and Var5 = ESPA  and Var6 = DG
Var3 = MU  and Var5 = FINL  and Var6 = DG
Var3 = MU  and Var5 = GRBR  and Var6 = DD
Var3 = MU  and Var5 = GREC  and Var6 = DG
Var3 = MU  and Var5 = HOLL  and Var6 = DG
Var3 = MU  and Var5 = IRLA  and Var6 = DD
Var3 = MU  and Var5 = ISLA  and Var6 = DG
Var3 = MU  and Var5 = ITAL  and Var6 = DG
Var3 = MU  and Var5 = NORV  and Var6 = DG
Var3 = MU  and Var5 = PORT  and Var6 = DG
Var3 = MU  and Var5 = SUED  and Var6 = DG
Var3 = MU  and Var5 = SUIS  and Var6 = DG
Var3 = MU  and Var5 = YOUG  and Var6 = DG
Var3 = MU  and Var5 = MAGH  and Var6 = DG
Var3 = MU  and Var5 = TURQ  and Var6 = DG
Var3 = MU  and Var5 = ARGE  and Var6 = DG
Var3 = MU  and Var5 = BRES  and Var6 = DG
Var3 = MU  and Var5 = CHIL  and Var6 = DG
Var3 = MU  and Var5 = COLO  and Var6 = DG
Var3 = MU  and Var5 = AFSU  and Var6 = DD
Var3 = MU  and Var5 = MARO  and Var6 = DG
Var3 = MU  and Var5 = ISRA  and Var6 = DG
Var3 = MU  and Var5 = HONG  and Var6 = DG
Var3 = MU  and Var5 = TCHE  and Var6 = DG
Var3 = MU  and Var5 = POLO  and Var6 = DG
Var3 = MU  and Var5 = SLVQ  and Var6 = DG
Var3 = MU  and Var5 = JAPO  and Var6 = DD
Var3 = MU  and Var5 = TAIW  and Var6 = DG
Var3 = MU  and Var5 = AUST  and Var6 = DD
Var3 = MU  and Var5 = URUG  and Var6 = DG
Var3 = MU  and Var5 = DAIB  and Var6 = DG
Var3 = MU  and Var5 = DAIC  and Var6 = DG
Var3 = MU  and Var5 = DAID  and Var6 = DD
Var3 = MU  and Var5 = DAIF  and Var6 = DG
Var3 = MU  and Var5 = EUOR  and Var6 = DG
Var3 = MU  and Var5 = CETI  and Var6 = DG
Var3 = MN  and Var5 = FRAN  and Var6 = DG
Var3 = MN  and Var5 = DOTO  and Var6 = DG
Var3 = MN  and Var5 = ALLE  and Var6 = DG
Var3 = MN  and Var5 = AUTR  and Var6 = DG
Var3 = MN  and Var5 = BELG  and Var6 = DG
Var3 = MN  and Var5 = DANE  and Var6 = DG
Var3 = MN  and Var5 = ESPA  and Var6 = DG
Var3 = MN  and Var5 = FINL  and Var6 = DG
Var3 = MN  and Var5 = GRBR  and Var6 = DD
Var3 = MN  and Var5 = GREC  and Var6 = DG
Var3 = MN  and Var5 = HOLL  and Var6 = DG
Var3 = MN  and Var5 = IRLA  and Var6 = DD
Var3 = MN  and Var5 = ISLA  and Var6 = DG
Var3 = MN  and Var5 = ITAL  and Var6 = DG
Var3 = MN  and Var5 = NORV  and Var6 = DG
Var3 = MN  and Var5 = PORT  and Var6 = DG
Var3 = MN  and Var5 = SUED  and Var6 = DG
Var3 = MN  and Var5 = SUIS  and Var6 = DG
Var3 = MN  and Var5 = YOUG  and Var6 = DG
Var3 = MN  and Var5 = MAGH  and Var6 = DG
Var3 = MN  and Var5 = TURQ  and Var6 = DG
Var3 = MN  and Var5 = ARGE  and Var6 = DG
Var3 = MN  and Var5 = BRES  and Var6 = DG
Var3 = MN  and Var5 = CHIL  and Var6 = DG
Var3 = MN  and Var5 = COLO  and Var6 = DG
Var3 = MN  and Var5 = AFSU  and Var6 = DD
Var3 = MN  and Var5 = MARO  and Var6 = DG
Var3 = MN  and Var5 = ISRA  and Var6 = DG
Var3 = MN  and Var5 = HONG  and Var6 = DG
Var3 = MN  and Var5 = TCHE  and Var6 = DG
Var3 = MN  and Var5 = POLO  and Var6 = DG
Var3 = MN  and Var5 = SLVQ  and Var6 = DG
Var3 = MN  and Var5 = JAPO  and Var6 = DD
Var3 = MN  and Var5 = TAIW  and Var6 = DG
Var3 = MN  and Var5 = AUST  and Var6 = DD
Var3 = MN  and Var5 = URUG  and Var6 = DG
Var3 = MN  and Var5 = DAIB  and Var6 = DG
Var3 = MN  and Var5 = DAIC  and Var6 = DG
Var3 = MN  and Var5 = DAID  and Var6 = DD
Var3 = MN  and Var5 = DAIF  and Var6 = DG
Var3 = MN  and Var5 = EUOR  and Var6 = DG
Var3 = MN  and Var5 = CETI  and Var6 = DG
Var3 = MH  and Var5 = FRAN  and Var6 = DG
Var3 = MH  and Var5 = DOTO  and Var6 = DG
Var3 = MH  and Var5 = ALLE  and Var6 = DG
Var3 = MH  and Var5 = AUTR  and Var6 = DG
Var3 = MH  and Var5 = BELG  and Var6 = DG
Var3 = MH  and Var5 = DANE  and Var6 = DG
Var3 = MH  and Var5 = ESPA  and Var6 = DG
Var3 = MH  and Var5 = FINL  and Var6 = DG
Var3 = MH  and Var5 = GRBR  and Var6 = DD
Var3 = MH  and Var5 = GREC  and Var6 = DG
Var3 = MH  and Var5 = HOLL  and Var6 = DG
Var3 = MH  and Var5 = IRLA  and Var6 = DD
Var3 = MH  and Var5 = ISLA  and Var6 = DG
Var3 = MH  and Var5 = ITAL  and Var6 = DG
Var3 = MH  and Var5 = NORV  and Var6 = DG
Var3 = MH  and Var5 = PORT  and Var6 = DG
Var3 = MH  and Var5 = SUED  and Var6 = DG
Var3 = MH  and Var5 = SUIS  and Var6 = DG
Var3 = MH  and Var5 = YOUG  and Var6 = DG
Var3 = MH  and Var5 = MAGH  and Var6 = DG
Var3 = MH  and Var5 = TURQ  and Var6 = DG
Var3 = MH  and Var5 = ARGE  and Var6 = DG
Var3 = MH  and Var5 = BRES  and Var6 = DG
Var3 = MH  and Var5 = CHIL  and Var6 = DG
Var3 = MH  and Var5 = COLO  and Var6 = DG
Var3 = MH  and Var5 = AFSU  and Var6 = DD
Var3 = MH  and Var5 = MARO  and Var6 = DG
Var3 = MH  and Var5 = ISRA  and Var6 = DG
Var3 = MH  and Var5 = HONG  and Var6 = DG
Var3 = MH  and Var5 = TCHE  and Var6 = DG
Var3 = MH  and Var5 = POLO  and Var6 = DG
Var3 = MH  and Var5 = SLVQ  and Var6 = DG
Var3 = MH  and Var5 = JAPO  and Var6 = DG
Var3 = MH  and Var5 = TAIW  and Var6 = DG
Var3 = MH  and Var5 = AUST  and Var6 = DD
Var3 = MH  and Var5 = URUG  and Var6 = DG
Var3 = MH  and Var5 = DAIB  and Var6 = DG
Var3 = MH  and Var5 = DAIC  and Var6 = DG
Var3 = MH  and Var5 = DAID  and Var6 = DD
Var3 = MH  and Var5 = DAIF  and Var6 = DG
Var3 = MH  and Var5 = EUOR  and Var6 = DG
Var3 = MH  and Var5 = CETI  and Var6 = DG
Var3 = MG  and Var5 = FRAN  and Var6 = DG
Var3 = MG  and Var5 = DOTO  and Var6 = DG
Var3 = MG  and Var5 = ALLE  and Var6 = DG
Var3 = MG  and Var5 = AUTR  and Var6 = DG
Var3 = MG  and Var5 = BELG  and Var6 = DG
Var3 = MG  and Var5 = DANE  and Var6 = DG
Var3 = MG  and Var5 = ESPA  and Var6 = DG
Var3 = MG  and Var5 = FINL  and Var6 = DG
Var3 = MG  and Var5 = GRBR  and Var6 = DD
Var3 = MG  and Var5 = GREC  and Var6 = DG
Var3 = MG  and Var5 = HOLL  and Var6 = DG
Var3 = MG  and Var5 = IRLA  and Var6 = DD
Var3 = MG  and Var5 = ISLA  and Var6 = DG
Var3 = MG  and Var5 = ITAL  and Var6 = DG
Var3 = MG  and Var5 = NORV  and Var6 = DG
Var3 = MG  and Var5 = PORT  and Var6 = DG
Var3 = MG  and Var5 = SUED  and Var6 = DG
Var3 = MG  and Var5 = SUIS  and Var6 = DG
Var3 = MG  and Var5 = YOUG  and Var6 = DG
Var3 = MG  and Var5 = MAGH  and Var6 = DG
Var3 = MG  and Var5 = TURQ  and Var6 = DG
Var3 = MG  and Var5 = ARGE  and Var6 = DG
Var3 = MG  and Var5 = BRES  and Var6 = DG
Var3 = MG  and Var5 = CHIL  and Var6 = DG
Var3 = MG  and Var5 = COLO  and Var6 = DG
Var3 = MG  and Var5 = AFSU  and Var6 = DD
Var3 = MG  and Var5 = MARO  and Var6 = DG
Var3 = MG  and Var5 = ISRA  and Var6 = DG
Var3 = MG  and Var5 = HONG  and Var6 = DG
Var3 = MG  and Var5 = TCHE  and Var6 = DG
Var3 = MG  and Var5 = POLO  and Var6 = DG
Var3 = MG  and Var5 = SLVQ  and Var6 = DG
Var3 = MG  and Var5 = JAPO  and Var6 = DD
Var3 = MG  and Var5 = TAIW  and Var6 = DG
Var3 = MG  and Var5 = AUST  and Var6 = DD
Var3 = MG  and Var5 = URUG  and Var6 = DG
Var3 = MG  and Var5 = DAIB  and Var6 = DG
Var3 = MG  and Var5 = DAIC  and Var6 = DG
Var3 = MG  and Var5 = DAID  and Var6 = DD
Var3 = MG  and Var5 = DAIF  and Var6 = DG
Var3 = MG  and Var5 = EUOR  and Var6 = DG
Var3 = MG  and Var5 = CETI  and Var6 = DG
Var3 = MY  and Var5 = FRAN  and Var6 = DG
Var3 = MY  and Var5 = DOTO  and Var6 = DG
Var3 = MY  and Var5 = ALLE  and Var6 = DG
Var3 = MY  and Var5 = AUTR  and Var6 = DG
Var3 = MY  and Var5 = BELG  and Var6 = DG
Var3 = MY  and Var5 = DANE  and Var6 = DG
Var3 = MY  and Var5 = ESPA  and Var6 = DG
Var3 = MY  and Var5 = FINL  and Var6 = DG
Var3 = MY  and Var5 = GRBR  and Var6 = DD
Var3 = MY  and Var5 = GREC  and Var6 = DG
Var3 = MY  and Var5 = HOLL  and Var6 = DG
Var3 = MY  and Var5 = IRLA  and Var6 = DD
Var3 = MY  and Var5 = ISLA  and Var6 = DG
Var3 = MY  and Var5 = ITAL  and Var6 = DG
Var3 = MY  and Var5 = NORV  and Var6 = DG
Var3 = MY  and Var5 = PORT  and Var6 = DG
Var3 = MY  and Var5 = SUED  and Var6 = DG
Var3 = MY  and Var5 = SUIS  and Var6 = DG
Var3 = MY  and Var5 = YOUG  and Var6 = DG
Var3 = MY  and Var5 = MAGH  and Var6 = DG
Var3 = MY  and Var5 = TURQ  and Var6 = DG
Var3 = MY  and Var5 = ARGE  and Var6 = DG
Var3 = MY  and Var5 = BRES  and Var6 = DG
Var3 = MY  and Var5 = CHIL  and Var6 = DG
Var3 = MY  and Var5 = COLO  and Var6 = DG
Var3 = MY  and Var5 = AFSU  and Var6 = DD
Var3 = MY  and Var5 = MARO  and Var6 = DG
Var3 = MY  and Var5 = ISRA  and Var6 = DG
Var3 = MY  and Var5 = HONG  and Var6 = DG
Var3 = MY  and Var5 = TCHE  and Var6 = DG
Var3 = MY  and Var5 = POLO  and Var6 = DG
Var3 = MY  and Var5 = SLVQ  and Var6 = DG
Var3 = MY  and Var5 = JAPO  and Var6 = DD
Var3 = MY  and Var5 = TAIW  and Var6 = DG
Var3 = MY  and Var5 = AUST  and Var6 = DD
Var3 = MY  and Var5 = URUG  and Var6 = DG
Var3 = MY  and Var5 = DAIB  and Var6 = DG
Var3 = MY  and Var5 = DAIC  and Var6 = DG
Var3 = MY  and Var5 = DAID  and Var6 = DD
Var3 = MY  and Var5 = DAIF  and Var6 = DG
Var3 = MY  and Var5 = EUOR  and Var6 = DG
Var3 = MY  and Var5 = CETI  and Var6 = DG
Var3 = NM2K  and Var5 = FRAN  and Var6 = DG
Var3 = NM2K  and Var5 = DOTO  and Var6 = DG
Var3 = NM2K  and Var5 = ALLE  and Var6 = DG
Var3 = NM2K  and Var5 = AUTR  and Var6 = DG
Var3 = NM2K  and Var5 = BELG  and Var6 = DG
Var3 = NM2K  and Var5 = DANE  and Var6 = DG
Var3 = NM2K  and Var5 = ESPA  and Var6 = DG
Var3 = NM2K  and Var5 = FINL  and Var6 = DG
Var3 = NM2K  and Var5 = GRBR  and Var6 = DD
Var3 = NM2K  and Var5 = GREC  and Var6 = DG
Var3 = NM2K  and Var5 = HOLL  and Var6 = DG
Var3 = NM2K  and Var5 = IRLA  and Var6 = DD
Var3 = NM2K  and Var5 = ISLA  and Var6 = DG
Var3 = NM2K  and Var5 = ITAL  and Var6 = DG
Var3 = NM2K  and Var5 = NORV  and Var6 = DG
Var3 = NM2K  and Var5 = PORT  and Var6 = DG
Var3 = NM2K  and Var5 = SUED  and Var6 = DG
Var3 = NM2K  and Var5 = SUIS  and Var6 = DG
Var3 = NM2K  and Var5 = YOUG  and Var6 = DG
Var3 = NM2K  and Var5 = MAGH  and Var6 = DG
Var3 = NM2K  and Var5 = TURQ  and Var6 = DG
Var3 = NM2K  and Var5 = ARGE  and Var6 = DG
Var3 = NM2K  and Var5 = BRES  and Var6 = DG
Var3 = NM2K  and Var5 = CHIL  and Var6 = DG
Var3 = NM2K  and Var5 = COLO  and Var6 = DG
Var3 = NM2K  and Var5 = AFSU  and Var6 = DD
Var3 = NM2K  and Var5 = MARO  and Var6 = DG
Var3 = NM2K  and Var5 = ISRA  and Var6 = DG
Var3 = NM2K  and Var5 = HONG  and Var6 = DG
Var3 = NM2K  and Var5 = TCHE  and Var6 = DG
Var3 = NM2K  and Var5 = POLO  and Var6 = DG
Var3 = NM2K  and Var5 = SLVQ  and Var6 = DG
Var3 = NM2K  and Var5 = JAPO  and Var6 = DD
Var3 = NM2K  and Var5 = TAIW  and Var6 = DG
Var3 = NM2K  and Var5 = AUST  and Var6 = DD
Var3 = NM2K  and Var5 = URUG  and Var6 = DG
Var3 = NM2K  and Var5 = DAIB  and Var6 = DG
Var3 = NM2K  and Var5 = DAIC  and Var6 = DG
Var3 = NM2K  and Var5 = DAID  and Var6 = DD
Var3 = NM2K  and Var5 = DAIF  and Var6 = DG
Var3 = NM2K  and Var5 = EUOR  and Var6 = DG
Var3 = NM2K  and Var5 = CETI  and Var6 = DG
Var3 = NM0C  and Var5 = FRAN  and Var6 = DG
Var3 = NM0C  and Var5 = DOTO  and Var6 = DG
Var3 = NM0C  and Var5 = ALLE  and Var6 = DG
Var3 = NM0C  and Var5 = AUTR  and Var6 = DG
Var3 = NM0C  and Var5 = BELG  and Var6 = DG
Var3 = NM0C  and Var5 = DANE  and Var6 = DG
Var3 = NM0C  and Var5 = ESPA  and Var6 = DG
Var3 = NM0C  and Var5 = FINL  and Var6 = DG
Var3 = NM0C  and Var5 = GRBR  and Var6 = DD
Var3 = NM0C  and Var5 = GREC  and Var6 = DG
Var3 = NM0C  and Var5 = HOLL  and Var6 = DG
Var3 = NM0C  and Var5 = IRLA  and Var6 = DD
Var3 = NM0C  and Var5 = ISLA  and Var6 = DG
Var3 = NM0C  and Var5 = ITAL  and Var6 = DG
Var3 = NM0C  and Var5 = NORV  and Var6 = DG
Var3 = NM0C  and Var5 = PORT  and Var6 = DG
Var3 = NM0C  and Var5 = SUED  and Var6 = DG
Var3 = NM0C  and Var5 = SUIS  and Var6 = DG
Var3 = NM0C  and Var5 = YOUG  and Var6 = DG
Var3 = NM0C  and Var5 = MAGH  and Var6 = DG
Var3 = NM0C  and Var5 = TURQ  and Var6 = DG
Var3 = NM0C  and Var5 = ARGE  and Var6 = DG
Var3 = NM0C  and Var5 = BRES  and Var6 = DG
Var3 = NM0C  and Var5 = CHIL  and Var6 = DG
Var3 = NM0C  and Var5 = COLO  and Var6 = DG
Var3 = NM0C  and Var5 = AFSU  and Var6 = DD
Var3 = NM0C  and Var5 = MARO  and Var6 = DG
Var3 = NM0C  and Var5 = ISRA  and Var6 = DG
Var3 = NM0C  and Var5 = HONG  and Var6 = DG
Var3 = NM0C  and Var5 = TCHE  and Var6 = DG
Var3 = NM0C  and Var5 = POLO  and Var6 = DG
Var3 = NM0C  and Var5 = SLVQ  and Var6 = DG
Var3 = NM0C  and Var5 = JAPO  and Var6 = DD
Var3 = NM0C  and Var5 = TAIW  and Var6 = DG
Var3 = NM0C  and Var5 = AUST  and Var6 = DD
Var3 = NM0C  and Var5 = URUG  and Var6 = DG
Var3 = NM0C  and Var5 = DAIB  and Var6 = DG
Var3 = NM0C  and Var5 = DAIC  and Var6 = DG
Var3 = NM0C  and Var5 = DAID  and Var6 = DD
Var3 = NM0C  and Var5 = DAIF  and Var6 = DG
Var3 = NM0C  and Var5 = EUOR  and Var6 = DG
Var3 = NM0C  and Var5 = CETI  and Var6 = DG
Var3 = ND1G  and Var5 = FRAN  and Var6 = DG
Var3 = ND1G  and Var5 = DOTO  and Var6 = DG
Var3 = ND1G  and Var5 = ALLE  and Var6 = DG
Var3 = ND1G  and Var5 = AUTR  and Var6 = DG
Var3 = ND1G  and Var5 = BELG  and Var6 = DG
Var3 = ND1G  and Var5 = DANE  and Var6 = DG
Var3 = ND1G  and Var5 = ESPA  and Var6 = DG
Var3 = ND1G  and Var5 = FINL  and Var6 = DG
Var3 = ND1G  and Var5 = GRBR  and Var6 = DD
Var3 = ND1G  and Var5 = GREC  and Var6 = DG
Var3 = ND1G  and Var5 = HOLL  and Var6 = DG
Var3 = ND1G  and Var5 = IRLA  and Var6 = DD
Var3 = ND1G  and Var5 = ISLA  and Var6 = DG
Var3 = ND1G  and Var5 = ITAL  and Var6 = DG
Var3 = ND1G  and Var5 = NORV  and Var6 = DG
Var3 = ND1G  and Var5 = PORT  and Var6 = DG
Var3 = ND1G  and Var5 = SUED  and Var6 = DG
Var3 = ND1G  and Var5 = SUIS  and Var6 = DG
Var3 = ND1G  and Var5 = YOUG  and Var6 = DG
Var3 = ND1G  and Var5 = MAGH  and Var6 = DG
Var3 = ND1G  and Var5 = TURQ  and Var6 = DG
Var3 = ND1G  and Var5 = ARGE  and Var6 = DG
Var3 = ND1G  and Var5 = BRES  and Var6 = DG
Var3 = ND1G  and Var5 = CHIL  and Var6 = DG
Var3 = ND1G  and Var5 = COLO  and Var6 = DG
Var3 = ND1G  and Var5 = AFSU  and Var6 = DD
Var3 = ND1G  and Var5 = MARO  and Var6 = DG
Var3 = ND1G  and Var5 = ISRA  and Var6 = DG
Var3 = ND1G  and Var5 = HONG  and Var6 = DG
Var3 = ND1G  and Var5 = TCHE  and Var6 = DG
Var3 = ND1G  and Var5 = POLO  and Var6 = DG
Var3 = ND1G  and Var5 = SLVQ  and Var6 = DG
Var3 = ND1G  and Var5 = JAPO  and Var6 = DD
Var3 = ND1G  and Var5 = TAIW  and Var6 = DG
Var3 = ND1G  and Var5 = AUST  and Var6 = DD
Var3 = ND1G  and Var5 = URUG  and Var6 = DG
Var3 = ND1G  and Var5 = DAIB  and Var6 = DG
Var3 = ND1G  and Var5 = DAIC  and Var6 = DG
Var3 = ND1G  and Var5 = DAID  and Var6 = DD
Var3 = ND1G  and Var5 = DAIF  and Var6 = DG
Var3 = ND1G  and Var5 = EUOR  and Var6 = DG
Var3 = ND1G  and Var5 = CETI  and Var6 = DG
or)