or(
Var5 = FRAN  and Var53 = SSPFIL
Var5 = DOTO  and Var53 = SSPFIL
Var5 = ALLE  and Var53 = SSPFIL
Var5 = AUTR  and Var53 = SSPFIL
Var5 = BELG  and Var53 = SSPFIL
Var5 = DANE  and Var53 = SSPFIL
Var5 = ESPA  and Var53 = SSPFIL
Var5 = FINL  and Var53 = SSPFIL
Var5 = GRBR  and Var53 = SSPFIL
Var5 = GREC  and Var53 = SSPFIL
Var5 = HOLL  and Var53 = SSPFIL
Var5 = IRLA  and Var53 = SSPFIL
Var5 = ISLA  and Var53 = SSPFIL
Var5 = ITAL  and Var53 = SSPFIL
Var5 = NORV  and Var53 = SSPFIL
Var5 = PORT  and Var53 = SSPFIL
Var5 = SUED  and Var53 = SSPFIL
Var5 = SUIS  and Var53 = SSPFIL
Var5 = YOUG  and Var53 = SSPFIL
Var5 = MAGH  and Var53 = AVPFIL
Var5 = TURQ  and Var53 = SSPFIL
Var5 = ARGE  and Var53 = SSPFIL
Var5 = BRES  and Var53 = SSPFIL
Var5 = CHIL  and Var53 = SSPFIL
Var5 = COLO  and Var53 = SSPFIL
Var5 = AFSU  and Var53 = SSPFIL
Var5 = MARO  and Var53 = AVPFIL
Var5 = ISRA  and Var53 = SSPFIL
Var5 = HONG  and Var53 = SSPFIL
Var5 = TCHE  and Var53 = SSPFIL
Var5 = POLO  and Var53 = SSPFIL
Var5 = SLVQ  and Var53 = SSPFIL
Var5 = JAPO  and Var53 = SSPFIL
Var5 = TAIW  and Var53 = SSPFIL
Var5 = AUST  and Var53 = SSPFIL
Var5 = URUG  and Var53 = SSPFIL
Var5 = DAIB  and Var53 = AVPFIL
Var5 = DAIC  and Var53 = SSPFIL
Var5 = DAID  and Var53 = SSPFIL
Var5 = DAIF  and Var53 = AVPFIL
Var5 = EUOR  and Var53 = SSPFIL
Var5 = CETI  and Var53 = AVPFIL
or)